_target_: src.models.LatentDiffusionModule

ema_decay: 0.995                  # EMA decay factor
#train_lr: 1e-4                    # Learning rate for training
#train_num_steps: 100000           # Total number of training steps
gradient_accumulate_every:  2 #8      # Number of steps to accumulate gradients before an optimizer update
amp: true                        # Use mixed precision training (true/false)
step_start_ema: 2000              # Start EMA updates after this many steps
update_ema_every: 10              # Frequency (in steps) to update the EMA model
save_and_sample_every:  1000       # Frequency (in steps) to save checkpoints and generate samples
results_folder: ${hydra:runtime.output_dir}       # Folder to save checkpoints and sample outputs
num_sample_rows: 1                # Number of rows in the grid when visualizing samples
max_grad_norm: 0.5 #null               # Maximum gradient norm for clipping (set to null if not used)
batch_size: ${data.batch_size} 
cache_dir:  ${paths.cache_dir}                  # Batch size for training

unet3d:
  _target_: src.models.ddpm.Unet3D
  dim: 64 #${data.dim} # 64  #this has to be the same as the vqgan now           # Spatial resolution, must match diffusion.image_size
  dim_mults: [1, 2, 4, 8]           # Multiplicative factors for channel scaling at each resolution
  channels: 4         # Number of channels (idk why we have 8 but ask later)

diffusion:
  _target_: src.models.ddpm.GaussianDiffusion
  denoise_fn: src.models.ddpm.Unet3D
  image_size: 28 # ${data.dim} #this has to be the same as the vqgan now                   
  num_frames: 28 # ${data.dim}   #this has to be the same as the vqgan now                      
  timesteps: 300                   # Total number of diffusion steps
  loss_type: "l2"                   # Type of loss ("l1" or "l2")
  channels: 4 #1 # we have grayscale input for now (i.e., x, y, z input not c, x, y, z or some variation)
  vqgan_ckpt: /home/sampath/VertebralDiffusion/logs/train_vqgan_seg/runs/2025-04-29_20-46-55/checkpoints/last.ckpt
  cache_dir: ${paths.cache_dir} # Path to the cache directory for storing intermediate results


optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 2e-5
  eps: 1e-08
  betas: [0.9, 0.999]
  weight_decay: 0.01
                 

lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts # gonna use warm restart for hopefully escaping local minima 
  _partial_: true                    # Optional: allows partial instantiation if desired
  optimizer: ${model.optimizer}            # Interpolates the optimizer config defined elsewhere
  T_0: 3000 #17590 # every epoch restart #8795 batches/epoch  but every 8 batches 1 step due to grad accum                        # First restart after 50 epochs
  T_mult: 2                       # Each cycle has the same duration (50 epochs)
  eta_min: 1e-8                   # Minimum learning rate at the end of each cycle
  last_epoch: -1                  # Start counting from the beginning
  verbose: True                  # Set to True if you want to see restart messages
  
  
  #T_max: 150
  #eta_min: 1e-8
