_target_: src.models.vq_gan_3d.VQGAN3D

embedding_dim: 64 # Needs to be the same as n_hiddens * 2**(downsample-1)
n_codes: 2048
lr: 3e-4

# encoder/decoder args
n_hiddens: 32
downsample: [2,2,2]
image_channels: 3
norm_type: group
padding_type: replicate
num_groups: 32

# codebook specific
no_random_restart: False
restart_thres: 1.0

# discriminator args
disc_channels: 64
disc_layers: 3
discriminator_iter_start: 50000
disc_loss_type: hinge


image_gan_weight: 1.0
video_gan_weight: 1.0
l1_weight: 4.0
gan_feat_weight: 1.0
perceptual_weight: 1.0

# Not used
# i3d_feat: False
# global_emb_dim: 8