# @package _global_

defaults:
  - _self_
  - data: vertebrae # choose datamodule with `test_dataloader()` for evaluation
  - model: vqgan3d_seg #latent_diffusion #vqgan3d_seg #diffusion #vqgan3d
  - logger: wandb
  - trainer: gpu
  - paths: tetris
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
